#!/bin/bash
# hier moeten variablen in
# de regel hieronder is gedisabled omdat het downloaden lang duurt
#cat gene_ids | sed 's@.*@https://www.ncbi.nlm.nih.gov/gene/?term=&@g' | wget -O- -i- -q | sed 's/>/\n/g' | grep span | grep \\.\\. | grep -v \\.\\.\\. | cut -d\< -f1 > genPositie
# slaat lengte gen op als coordnaten
# de regel hieronder is gedisabled omdat het downloaden lang duurt
#cat gene_ids | sed 's@.*@https://www.ncbi.nlm.nih.gov/gene/?term=&@g' | wget -O- -i- -q | sed 's/>/\n/g' | grep \/title | cut -d\  -f1 > genenMetNaam

pr -Jmt genPositie gene_ids genenMetNaam | awk '{split($1, a, ".");print $(NF-1), $NF, "NULL", a[3]-a[1]}' > genIDLength
# slaat de genlengte op icm gen id

