#!/bin/bash
#cat exon_table_full | awk 'BEGIN{q=1;m=""}{split($4, w, "-");if (m == $1){q++} else {m=$1;q=1}if (w[2] != "") {print q,substr($1, 2),w[1],w[2]}}' > vullDataBase && echo $1 | sudo -S su - postgres -c "psql `cat .postSettings` <<< \"1234hello
#COPY EXON_14 FROM '`pwd`/vullDataBase' DELIMITER ' '\""
# hierboven doet het op systeem waar server == client
# hieronder waar server == wndws AND client == WSL
# aka windows subsystem linux
# cd ../realwrldTest && ../dataBase/genLengte \
cd $1
if test "$2" = "";then
	read -s token
else
	token=$2
fi

cd $3 \
&& cp genIDLength ../vullDataBase \
&& cd ../dataBase \
&& echo $2 | sudo -S su - postgres -c "psql `cat .postSettings` <<< \"
COPY GEN_14 FROM '$PWD/../vullDataBase' DELIMITER ' ' NULL AS 'NULL'\"" \
&& cd $1 \
&& cp dataStuffExon ../vullDataBase \
&& cd ../dataBase \
&& echo $token | sudo -S su - postgres -c "psql `cat .postSettings` <<< \"
COPY EXON_14 FROM '$PWD/../vullDataBase' DELIMITER ' ' NULL AS 'NULL'\"" \
&& echo good bye \
&& cd $1 \
&& cp genEiwitExon ../vullDataBase \
&& cd ../dataBase \
&& echo $token | sudo -S su - postgres -c "psql `cat .postSettings` <<< \"
COPY KOPPEL_14 FROM '$PWD/../vullDataBase' DELIMITER '%' NULL AS 'NULL'\"" \
&& echo helloThere \
&& cd $1 \
&& cp proTijdelijk ../vullDataBase \
&& cd ../dataBase \
&& echo $token | sudo -S su - postgres -c "psql `cat .postSettings` <<< \"
COPY EIWIT_14 FROM '$PWD/../vullDataBase' DELIMITER '#' NULL AS 'NULL'\""\
&& cd $1 \
&& cp asnkoppelpathwayMoter ../vullDataBase \
&& cd ../dataBase \
&& echo $token | sudo -S su - postgres -c "psql `cat .postSettings` <<< \"
COPY PATHWAY_KOPPEL FROM '$PWD/../vullDataBase' DELIMITER '^' NULL AS 'NULL'\""\
&& cd $1 \
&& cp ECKoppelMoter ../vullDataBase \
&& cd ../dataBase \
&& echo $token | sudo -S su - postgres -c "psql `cat .postSettings` <<< \"
COPY EC_koppel FROM '$PWD/../vullDataBase' DELIMITER '\$' NULL AS 'NULL'\""\
&& cd $1 \
&& cp test_ec_naam ../vullDataBase \
&& cd ../dataBase \
&& echo $token | sudo -S su - postgres -c "psql `cat .postSettings` <<< \"
COPY EC_14 FROM '$PWD/../vullDataBase' DELIMITER '~' NULL AS 'NULL'\"" \
&& cd $1 \
&& cp pathwayOutput ../vullDataBase \
&& cd ../dataBase \
&& echo $token | sudo -S su - postgres -c "psql `cat .postSettings` <<< \"
COPY PATHWAY_SHADOW_14 FROM '$PWD/../vullDataBase' DELIMITER '%' NULL AS 'NULL'\""
#koppelASNMoter|pathwayMoter
# verplaats vullDataBase naar een plaats waar rechten zijn
